title = "Nara"
author = "Nara Omur"
description = "Engineer | Thinker | Learner"
profilePicture = "images/naraomur.png"
favicon = "favicons/"
disableThemeSwitcher = true
contentRatio = 0.7
gtagId = "G-3QDB62WNH6"


mainSections = []

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/munaraomurbaeva"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/naraomur"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:naraomur@gmail.com"